spring:
  application:
    name: location_car

  # Configuration de la base de donnees
  datasource:
    url: jdbc:postgresql://localhost:5432/car_location
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver

  # Configuration de JPA/Hibernate
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuration Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: delfredtene17@gmail.com
    password: npzlkuetltimescg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Email de l'expediteur
app:
  mail:
    from: carrental@gmail.com
    fromName: Car Rental System
  base:
    url: http://localhost:8000/api

# Configuration du serveur
server:
  servlet:
    context-path: /api
  port: 8000